version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    command: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

volumes:
  postgres:
