services:
  postgres:
    container_name: postgres
    image: postgres:16-alpine
    command: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - type: tmpfs
        target: /var/lib/postgresql/data
      - type: tmpfs
        target: /dev/shm

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "4317:4317"

volumes:
  postgres:
