name: publish
on:
  workflow_dispatch:
  release:
    types:
      - published

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true
  NuGetDirectory: ${{ github.workspace}}/nuget

defaults:
  run:
    shell: pwsh

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      - name: Create Beckett NuGet Package
        run: dotnet pack src/Beckett/Beckett.csproj --configuration Release --output ${{ env.NuGetDirectory }}
      - name: Create Beckett.Dashboard NuGet Package
        run: dotnet pack src/Beckett.Dashboard/Beckett.Dashboard.csproj --configuration Release --output ${{ env.NuGetDirectory }}
      - name: Publish NuGet Package
        run: |
          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
